### PR TITLE
Add eslint as a peerDepency to this project.

### PR DESCRIPTION
**Pull request by aljones15**
just so eslint is there for sure on install.

### CODE REVIEW

**Comment by mattcollier** [comment]
Would any harm come from making `eslint` a regular dependency?  If we did that, then we don't have to track eslint dep in all of our modules.  Also, experience tells me that for a variety of reasons, people don't pay much attention to npm errors like missing peer deps.

**Comment by mattcollier** [comment]
Looking at airbnb, looks like they have eslint listed as *both* a devDependency and a peer dep?  https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base

**Comment by dlongley** [comment]
Seems like we should just make it a `devDependency`. That's the only time you need it. Not sure how making it a `peerDependency` helps as it will just generate a warning people won't read. I suppose it locks in a preferred version, but so would using `devDependency` (plus we'd get the install). Thoughts?

**Comment by mattcollier** [comment]
@dlongley if eslint is a dev dependency in this module and this module is a dev-dependency of module foo, does eslint get installed?

**Comment by aljones15** [comment]
you guys know better than me on this one (I have only worked in deps and devDeps never peer) so I will do whichever one you recommend.
also can expand this with test rules that include:

https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-mocha-arrows.md

if needed.

**Comment by dlongley** [comment]
@mattcollier,

> if eslint is a dev dependency in this module and this module is a dev-dependency of module foo, does eslint get installed?

Ugh, I guess not. I don't think that making it a `peerDependency` would do that either.

**Comment by aljones15** [comment]
> @mattcollier,
> 
> > if eslint is a dev dependency in this module and this module is a dev-dependency of module foo, does eslint get installed?
> 
> Ugh, I guess not. I don't think that making it a `peerDependency` would do that either.

actually that's the point of peerDepencies is that when you install this package it's peerDepencies install at the same time: 

https://nodejs.org/en/blog/npm/peer-dependencies/

Now, when installing chai-as-promised, the chai package will come along with it. And if later you try to install another Chai plugin that only works with 0.x versions of Chai, you'll get an error. Nice!

**Pull request merged**
